### ISSUE TITLE
download list

### ISSUE THREAD

**Issue by JRH-stanford** [Sihao/get_citing_authors#1]
on centos 7, python 2.7, I get the following trackback trace when I attempt to download a list:

    File "/home/httpd/users/huguenar/get_citing_authors/main.py", line 106, in return_csv
    return output_csv(author_list)
    File "/home/httpd/users/huguenar/get_citing_authors/utils.py", line 273, in output_csv
    writer.writerows(author_list)
    TypeError: unicode argument expected, got 'str'

this is what a dump of the first part of author_list object looks like:
[('Prince DA', 8, ('19187292'), ('27076424')), ('Parada I', 5, ('19187292'), ('25796572')), ('Li H', 3, ('19187292'), ('27020758')), ('McDonald W', 3, ('19187292'), ('25858773')), ('Wilson SM', 2, ('19187292'), ('23284921')), ('Faria LC', 2, ('19187292'), ('25858773')), ('Ma Y', 2, ('19187292'), ('22766033')), ('Jones BW', 2, ('19187292'), ('22963112')), ('Khanna R', 2, ('19187292'), ('21482550')), ('Prince D', 2, ('19187292'), ('25858773')), ('Imbrosci B', 2, ('19187292'), ('25858773')), ('Takahashi DK', 2, ('19187292'), ('24050267')), ('Jin X', 2, ('19187292'), ('21482550')), ('Mittmann T', 2, ('19187292'), ('27521191')),

**Comment by Sihao** [comment]
I'll have a look at it. Is it convenient for you to try running it with Python 3.6? 
That's what I'm using for development. I might be able to get it to work for either.

**Comment by JRH-stanford** [comment]
yes, it works with python 3.6.  This fixes many issues.  Thanks.  Also, I ran the following:

pip install -r requirements.txt

which may have been obvious to some, but not me, so if necessary perhaps make this step explicit in your install instructions.

**Comment by Sihao** [comment]
Aha, grand! I'll add it in.
